{{- if .Values.client_tls_sslmode.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pgbouncer.fullname" . }}-client
type: Opaque
data:
{{ toYaml .Values.tlsFiles | indent 2 }}
{{- end -}}
