{{- if .Values.client_tls_sslmode.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pgbouncer.fullname" . }}-client-tls
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{ toYaml .Values.tlsFiles | indent 2 }}
{{- end -}}
