apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pgbouncer.fullname" . }}
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  pgbouncer.ini: |-
{{ include "pgbouncer.ini.1.0.0" . | indent 4 }}
