apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pgbouncer.fullname" . }}
  labels:
    {{ template "pgbouncer.appLabel" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4}}
    {{- end }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pgbouncer.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pgbouncer.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "pgbouncer.fullname" . }}-secret
        {{- if .Values.client_tls_sslmode.enabled }}
        - name: tls
          secret:
            secretName: {{ template "pgbouncer.fullname" . }}-client
        {{- end }}
      containers:
        - name: pgbouncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: {{ .Values.internalPort }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.internalPort }}
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                # Allow existing queries clients to complete within 120 seconds
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['all']
          volumeMounts:
            - name: secret
              subPath: userlist.txt
              mountPath: /etc/pgbouncer/userlist.txt
              readOnly: true
            - name: secret
              subPath: pgbouncer.ini
              mountPath: /etc/pgbouncer/pgbouncer.ini
              readOnly: true
            {{- if .Values.client_tls_sslmode.enabled }}
            - name: tls
              mountPath: /etc/pgbouncer/tls
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

