{{- if .Values.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "pgbouncer.fullname" . }}"
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "pgbouncer.fullname" . }}
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.budget.minAvailable }}
{{- end -}}
