# Deployment values for pgbouncer
replicaCount: 1
internalPort: 5432
antiAffinity: soft

budget:
  minAvailable: 0

image:
  repository: chrisduong/pgbouncer
  tag: 1.8.1
  pullPolicy: Always

databases: {}
#  name:
#    host: host
#    port: port
#    user: user
#    dbname: dbname

users: {}
#  username: password

connectionLimits:
  maxClientConn: 200
  defaultPoolSize: 200
  minPoolSize: 15
  reservePoolSize: 25
  reservePoolTimeout: 5

labels: {}
# Add custom deployment labels here

logConnections: 0
logDisconnections: 0
logStats: 0
logPoolerErrors: 1
verbose: 0
statsPeriod: 60

# add key: value map entries to customSettings to be added to pbgouncer.ini [pgbouncer] section
customSettings: {}

global:
  # optionally use namespace as dbname
  namespacedDatabases: false

resources: {}

service:
  type: ClusterIP
  port: 5432
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""
  annotations: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

client_tls_sslmode:
  enabled: false
## Base64-encoded PEM values for server's CA certificate(s), certificate and private key
# tlsFiles:
#     ca:
#     cert:
#     key:
