name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install helm
        run: |
          helm init --client-only
          helm version --client
      - name: Test
        run: helm lint pgbouncer
      - name: Package the chart
        run: helm package pgbouncer
      - name: Upload the chart
        run: |
          VERSION=`sed -n -e 's/^version: //p' pgbouncer/Chart.yaml`
          curl -u${USER}:${PASSWORD} -T pgbouncer-${VERSION}.tgz "https://alfred.jfrog.io/alfred/charts/pgbouncer-${VERSION}.tgz"
          # TODO: parse JSON return to know the result.
        # $HELM_REPO_USERNAME $HELM_REPO_PASSWORD
        # Chartmeseum is not support in JFrog
        # run: helm push . https://alfred.jfrog.io/alfred/charts
